theforeman/smart_proxy_dynflow

lib/smart_proxy_dynflow/api.rb, smart_proxy_dynflow.gemspec, test/api_test.rb
Luckily, the Dynflow already contains the code we need.
Depends on https://github.com/Dynflow/dynflow/pull/163
=> Don't use active support features

lib/smart_proxy_dynflow.rb, lib/smart_proxy_dynflow/http_config.ru, lib/smart_proxy_dynflow/testing.rb
We can't initalize the dynflow world sooner than the smart proxy forks in
production, because otherwise we loose the file descriptors we need to open at
the initialization phase.
We also add a hooking mechanism for other plugins using dynflow/concurrent
ruby for after_initialization tasks
=> Postpone the Dynflow world initialization

Rakefile, lib/smart_proxy_dynflow.rb, lib/smart_proxy_dynflow/plugin.rb, settings.d/dynflow.yml.example
will need to create `/var/spool/foreman-proxy/dynflow` in package spec, see https://github.com/theforeman/foreman-packaging/blob/rpm/develop/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec#L5 for an example
=> Fixes #11366 - adds dynflow persistance

lib/smart_proxy_dynflow/testing.rb
No need to worry about the creation of the sqlite file then.
=> Fixes #13523 - use in-memory sqlite for tests

lib/smart_proxy_dynflow.rb, lib/smart_proxy_dynflow/plugin.rb, settings.d/dynflow.yml.example
Plain HTTP remains freely accessible, connections over HTTPS require a client SSL certificate
=> Fixes #11363 - Smart proxy dynflow console auth

lib/smart_proxy_dynflow.rb
Tests are failing due to change in smart proxy
```
/var/lib/workspace/workspace/test_proxy_plugin_matrix/ruby/2.0.0/lib/smart_proxy_dynflow.rb:25:in `persistence_conn_string': undefined method `logger' for Proxy::Log:Module (NoMethodError)
```
=> fixes #14314 - use logger instead of Proxy::Log for logging

config/settings.yml.example, lib/smart_proxy_dynflow/api.rb, lib/smart_proxy_dynflow/callback.rb, lib/smart_proxy_dynflow/plugin.rb, lib/smart_proxy_dynflow_core/callback.rb, lib/smart_proxy_dynflow_core/core.rb, lib/smart_proxy_dynflow_core/helpers.rb, lib/smart_proxy_dynflow_core/settings.rb, settings.d/dynflow.yml.example, test/api_test/api_test.rb, test/api_test/test_helper.rb
They might differ form the certs used for https.
Also, we now detect the need for certs based on the schema of the callback url.
I've updated the settings.yml.example to start with http by default, for
development purposes, not expecting the devels to have the certs in place.
The certs part in setting file I used when testing with Katello
looked something like this:
```
:ssl_ca_file:  /etc/foreman-proxy/ssl_ca.pem
:ssl_private_key: /etc/foreman-proxy/ssl_key.pem
:ssl_certificate: /etc/foreman-proxy/ssl_cert.pem
:foreman_ssl_ca:  /etc/foreman-proxy/foreman_ssl_ca.pem
:foreman_ssl_key: /etc/foreman-proxy/foreman_ssl_key.pem
:foreman_ssl_cert: /etc/foreman-proxy/foreman_ssl_cert.pem
```
=> Fixes #15442 - use separate settings for client certs

lib/smart_proxy_dynflow/plugin.rb, lib/smart_proxy_dynflow_core.rb, lib/smart_proxy_dynflow_core/api.rb, lib/smart_proxy_dynflow_core/callback.rb, lib/smart_proxy_dynflow_core/core.rb, lib/smart_proxy_dynflow_core/launcher.rb, lib/smart_proxy_dynflow_core/log.rb, lib/smart_proxy_dynflow_core/settings.rb, smart_proxy_dynflow_core.gemspec
This allows any gem using foreman-tasks-core to use both foreman and
smart proxy as the process for running it
=> Refs #16058 - integrate foreman-tasks-core

test/core_test/api_test.rb
It seems the `triggered.finished` finishes sooner than the persistence
is updated. Adding `wait_for` to check the state instead.
=> Fixes #20892 - better waiting for required state

smart_proxy_dynflow_core.gemspec
Without this, I'm getting the following error when running `bundle update` on smart-proxy (develop branch). I suppose the plugin can simply rely on sinatra/rack being provided by smart-proxy.
```
Resolving dependencies......
Bundler could not find compatible versions for gem "rack-protection":
In Gemfile:
smart_proxy was resolved to 1.17.0.develop, which depends on
sinatra was resolved to 1.4.6, which depends on
rack-protection (= 2.0.0)
smart_proxy_dynflow_core was resolved to 0.1.8, which depends on
sinatra (~> 1.4) was resolved to 1.4.6, which depends on
rack-protection (~> 1.4)
Bundler could not find compatible versions for gem "tilt":
In Gemfile:
smart_proxy was resolved to 1.17.0.develop, which depends on
sinatra was resolved to 1.4.0, which depends on
tilt (~> 2.0) …
```
=> Fixes #22141 - Remove sinatra/rack dependencies

lib/smart_proxy_dynflow/http_config.ru, lib/smart_proxy_dynflow/http_config_with_executor.ru, lib/smart_proxy_dynflow/plugin.rb, settings.d/dynflow.yml.example
The behavior can be configured using the `external_core` key in the settings.
If unset, the behavior will remain the same, eg. use internal core if available,
fallback to external core otherwise. Setting it to `true` will force the proxy to
always use an external core. Setting it to `false` will make the proxy try to
always use the internal core and disable the feature if it is not available.
=> Fixes #26969 - Allow using remote core even if core gem is available

lib/smart_proxy_dynflow/api.rb, lib/smart_proxy_dynflow_core/api.rb, lib/smart_proxy_dynflow_core/helpers.rb, smart_proxy_dynflow_core.gemspec, test/core_test/helpers_test.rb
Propagates external events to underlying action without invalidating the
OTP, so that it can be called multiple times.
Depends on:
=> Fixes #26691 - add `POST /tasks/:task_id/update` endpoint

lib/smart_proxy_dynflow_core/launcher.rb
Current setups shouldn't use TLS 1.1 anymore. PCI compliant setups are also required to disable it. By doing this out of the box, the software becomes more secure and more compliant.
=> Fixes #29624 - Stop accepting TLS 1.1

lib/smart_proxy_dynflow_core/log.rb
Automatic conversion was deprecated:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
This was giving: https://gist.github.com/lzap/24e0a7e10bcc45c9250e5a588f849b48
on Ruby 2.7+
=> Fix logging argument for Ruby 2.7

lib/smart_proxy_dynflow_core/log.rb
Before:
```
$ exec bin/smart_proxy_dynflow_core
D, [2020-07-01T15:18:18.451524 #2415322] DEBUG -- : Using HTTP
I, [2020-07-01T15:18:18.455993 #2415322]  INFO -- : WEBrick 1.4.2
I, [2020-07-01T15:18:18.456018 #2415322]  INFO -- : ruby 2.6.3 (2019-04-16) [x86_64-linux]
D, [2020-07-01T15:18:18.456826 #2415322] DEBUG -- : Rack::Handler::WEBrick is mounted on /.
Could not open DB for dynflow at '', will keep data in memory. Restart will drop all dynflow data.Execution plan cleaner removing 0 execution plans.WEBrick::HTTPServer#start: pid=2415322 port=8008accept: 127.0.0.1:42150Rack::Handler::WEBrick is invoked.require_ssl_client_verification: skipping, non-HTTPS request127.0.0.1 - - [01/Jul/2020:15:18:23 CEST] "GET /task/count? HTTP/1.1" 404 528
close: 127.0.0.1:42150Executor heartbeatExecutor …
```
=> Fixes #30278 - Fix missing newlines in logs

Gemfile
Solves the issue mentioned in the ticket. The logging gem uses auto loading capability and discovers all plugins automatically, there is no need to require it.
However if uses configures journald he/she must ensure the gem was installed otherwise it will error out.
=> Fixes #31352 - don't require logging-journald

lib/smart_proxy_dynflow_core/settings.rb
I've encountered the following issue when a plugin setting was nil
```
Traceback (most recent call last):
12: from /usr/bin/smart_proxy_dynflow_core:23:in `<main>'
11: from /usr/bin/smart_proxy_dynflow_core:23:in `load'
10: from /opt/theforeman/tfm/root/usr/share/gems/gems/smart_proxy_dynflow_core-0.2.6/bin/smart_proxy_dynflow_core:32:in `<top (required)>'
9: from /opt/theforeman/tfm/root/usr/share/gems/gems/smart_proxy_dynflow_core-0.2.6/lib/smart_proxy_dynflow_core/launcher.rb:13:in `launch!'
8: from /opt/theforeman/tfm/root/usr/share/gems/gems/smart_proxy_dynflow_core-0.2.6/lib/smart_proxy_dynflow_core/launcher.rb:17:in `start'
7: from /opt/theforeman/tfm/root/usr/share/gems/gems/smart_proxy_dynflow_core-0.2.6/lib/smart_proxy_dynflow_core/launcher.rb:36:in `load_settings!'
6: from …
```
=> Don't crash on plugin without a setting

smart_proxy_dynflow.gemspec
In e205e19a00d8ef269953811a3c4e5140776915b1 we've removed the dependency
on smart_proxy_dynflow_core, but we've forgotten to bring over the gem
runtime dependencies.
=> Refs #32534 - add forgotten deps from dynflow_core

lib/smart_proxy_dynflow/action/batch_callback.rb, lib/smart_proxy_dynflow/action/batch_runner.rb, lib/smart_proxy_dynflow/action/shareable.rb
Remove usage of SmartProxyDynflowCore.
=> Refs #32534 - dont use SmartProxyDynflowCore

smart_proxy_dynflow_core.gemspec
@adamruzicka I doubt this is the correct solution but it helps me illustrate the problem we are seeing on Debian installations:
```
Jun 23 01:32:57 debian10-64.example.com smart-proxy[10743]: /usr/lib/ruby/vendor_ruby/bundler_ext/output.rb:13:in `strict_err': Gem loading error: cannot load such file -- smart_proxy_dynflow (RuntimeError)
Jun 23 01:32:57 debian10-64.example.com smart-proxy[10743]:         from /usr/lib/ruby/vendor_ruby/bundler_ext/runtime.rb:46:in `rescue in block in system_require'
Jun 23 01:32:57 debian10-64.example.com smart-proxy[10743]:         from /usr/lib/ruby/vendor_ruby/bundler_ext/runtime.rb:39:in `block in system_require'
Jun 23 01:32:57 debian10-64.example.com smart-proxy[10743]:         from /usr/lib/ruby/vendor_ruby/bundler_ext/runtime.rb:37:in `each'
Jun 23 …
```
=> Require smart_proxy_dynflow by smart_proxy_dynflow_core

smart_proxy_dynflow.gemspec, smart_proxy_dynflow_core.gemspec
There is no real reason for not supporting ruby 3.
=> Fixes #32875 - Loosen required ruby version

lib/smart_proxy_dynflow/action/runner.rb
Output chunks are stored when the action is saved, but we we're aggregating them
into output[:result] before the final save so unsaved chunks didn't make it there.
=> Fixes #34092 - Store even non-commited output chunks on finish

lib/smart_proxy_dynflow/core.rb
If the DB file is /var/lib/foreman-proxy/dynflow/dynflow.sqlite and /var/lib/foreman-proxy/dynflow doesn't exist, it fails. This ensures the directory exists. In practice foreman-proxy already creates /var/lib/foreman-proxy so this should work.
I haven't had a chance to verify this. @janniswarnat do you have a chance to verify this solves your problem?
Another solution is to keep the DB in memory which can be achieved by leaving the setting empty. This is what the foreman-installer does by default.
=> Fixes #34616 - Create DB directory dynamically

lib/smart_proxy_dynflow/plugin.rb, settings.d/dynflow.yml.example
It will now wake up every half an hour and remove all execution plans
which have been stopped for at least half an hour. Half an hour should
give Foreman enough time to check up on the proxy in case the callback
from proxy fails, while not being too high at the same time.
=> Fixes #34625 - Make execution plan cleaner more aggressive

lib/smart_proxy_dynflow/api.rb, lib/smart_proxy_dynflow/helpers.rb, test/api_test.rb
for multiple execution plans in a single request
=> Fixes #35202 - Add API to expose details of execution plans

Gemfile, Rakefile, test/test_helper.rb
For refernce: https://github.com/theforeman/smart_proxy_dynflow/pull/123#issuecomment-1646601180
We have GitHub Action to run the tests against different Ruby versions.
=> Drop smart_proxy_dynflow Jenkins test changes

.github/workflows/ruby.yml, .rubocop.yml, smart_proxy_dynflow.gemspec
For refernce: https://github.com/theforeman/smart_proxy_dynflow/pull/122#issuecomment-1625472248
=> Drop Ruby 2.5 support

Rakefile
This turns on the GitHub formatter if GH Actions is detected, which provides nice inline annotations.
Right now I added a commit to force failures, which showcases the feature.
This replaces the last part of https://github.com/theforeman/smart_proxy_dynflow/pull/104
=> Improve RuboCop task definition in Rakefile

lib/smart_proxy_dynflow/continuous_output.rb, lib/smart_proxy_dynflow/runner/base.rb, lib/smart_proxy_dynflow/runner/parent.rb, test/runner_test.rb
and switch runner output interface to be keyword based.
=> Fixes #37319 - Allow setting IDs for outputs

smart_proxy_dynflow.gemspec
CI on ruby 3.3 started failing with
```
WARNING:  License identifier 'GPL-3.0' is deprecated. Use an identifier from
https://spdx.org/licenses or 'Nonstandard' for a nonstandard license,
or set it to nil if you don't want to specify a license.
Did you mean 'AFL-3.0', 'APL-1.0', 'CPL-1.0', 'EPL-1.0', 'EPL-2.0', 'IPL-1.0', 'LPL-1.0', 'MPL-1.0', 'MPL-2.0', 'NPL-1.0', 'OPL-1.0', 'OSL-3.0', 'QPL-1.0', 'SPL-1.0', 'TPL-1.0', 'UPL-1.0', 'YPL-1.0', 'ZPL-2.0'?
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
```
=> Use non-deprecated license identifier
